// Code generated by goctl. DO NOT EDIT.
// Source: study.proto

package server

import (
	"context"

	"demo-gateway/rpc/study/internal/logic/study"
	"demo-gateway/rpc/study/internal/svc"
	"demo-gateway/rpc/study/study"
)

type StudyServer struct {
	svcCtx *svc.ServiceContext
	study.UnimplementedStudyServer
}

func NewStudyServer(svcCtx *svc.ServiceContext) *StudyServer {
	return &StudyServer{
		svcCtx: svcCtx,
	}
}

func (s *StudyServer) Hello(ctx context.Context, in *study.HelloRequest) (*study.HelloResponse, error) {
	l := studylogic.NewHelloLogic(ctx, s.svcCtx)
	return l.Hello(in)
}

func (s *StudyServer) UserInfo(ctx context.Context, in *study.UserInfoRequest) (*study.UserInfoResponse, error) {
	l := studylogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
